<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageDescription>Intuitive Analogy Log Viewer Provider</PackageDescription>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<VersionPrefix>9.0.10</VersionPrefix>
		<VersionSuffix></VersionSuffix>
		<Authors>Lior Banai</Authors>
		<Product>Analogy.LogViewer.Intuitive</Product>
		<PackageId>Analogy.LogViewer.Intuitive</PackageId>
		<AssemblyName>Analogy.LogViewer.Intuitive</AssemblyName>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<AssemblyTitle>Analogy.LogViewer.Intuitive</AssemblyTitle>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Company>Lior Banai</Company>
		<Description>Analogy Log Parser for Intuitive Log Files</Description>
		<Copyright>Lior Banai © 2023-2026</Copyright>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageProjectUrl>https://github.com/Analogy-LogViewer/Analogy.LogViewer.Intuitive</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Analogy-LogViewer/Analogy.LogViewer.Intuitive</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReleaseNotes></PackageReleaseNotes>
		<PackageIcon>AnalogyIcon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIconUrl />
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
		<ApplicationIcon>AnalogyIcon.ico</ApplicationIcon>
		<ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
		<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="Analogy.LogViewer.ElasticCommonSchema" Version="9.0.6.1" />
		<PackageReference Include="Analogy.LogViewer.Interfaces" Version="9.0.6" />
		<PackageReference Include="Analogy.LogViewer.Serilog" Version="9.0.5" />
		<PackageReference Include="Analogy.LogViewer.Template" Version="9.0.6" />
		<PackageReference Include="Elastic.CommonSchema" Version="9.0.0" />
		<PackageReference Include="Elastic.CommonSchema.Serilog" Version="9.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="System.Text.Json" Version="10.0.9" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\AnalogyIcon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Content Include="AnalogyIcon.ico" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\unity.png" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\settings.png" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
	</ItemGroup>
</Project>
